# Generated by Django 4.0.4 on 2022-05-11 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(115), django.core.validators.MinValueValidator(16)])),
            ],
        ),
    ]
