name: Pull request into master

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master"]

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pytest test.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

  merge:
    name: merge
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Merge staging -> uat
      uses: devmasx/merge-branch@master
      with:
        type: now
        target_branch: uat
        github_token: ${{ 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 }}
